module.exports = {
  CHECK_EXISTING_ROOM: "CHECK_EXISTING_ROOM",
  VERIFY_USER: "VERIFY_USER",
  USER_CONNECTED_AND_CREATE_ROOM: "USER_CONNECTED_AND_CREATE_ROOM",
  USER_CONNECTED_AND_JOIN_ROOM: "USER_CONNECTED_AND_JOIN_ROOM",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  LIST_OF_USERS: "LIST_OF_USERS",
  SERVER_MESSAGE: "SERVER_MESSAGE",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  TYPING: "TYPING",
  LOGOUT: "LOGOUT"
};
