/**
 * @module constants костанты для событий
 */
module.exports = {
  CHECK_EXISTING_ROOM: "CHECK_EXISTING_ROOM",
  VERIFY_USER: "VERIFY_USER",
  USER_CONNECTED_AND_CREATE_ROOM: "USER_CONNECTED_AND_CREATE_ROOM",
  USER_CONNECTED_AND_JOIN_ROOM: "USER_CONNECTED_AND_JOIN_ROOM",
  LIST_OF_USERS: "LIST_OF_USERS",
  SERVER_SEND_MESSAGE: "SERVER_SEND_MESSAGE",
  USER_SEND_MESSAGE: "USER_SEND_MESSAGE",
  LOGOUT: "LOGOUT"
};
